-- Tabla configuracion
CREATE TABLE configuracion(
	id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	telefono_contacto CHAR(9) NOT NULL,
    email_contacto VARCHAR(200) NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla idiomas
CREATE TABLE idiomas (
  id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(50) NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  activo BOOLEAN NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla roles
CREATE TABLE roles (
  id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(50) NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla usuarios
CREATE TABLE usuarios(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    email VARCHAR(100) NULL,
    password VARCHAR(255) NOT NULL,
    usuario VARCHAR(30) NOT NULL,
	fecha_nacimiento DATE NOT NULL,
	telefono CHAR(9) NOT NULL,
	idioma_id INT UNSIGNED NOT NULL,
	CONSTRAINT UX_EMAIL UNIQUE (email),
	CONSTRAINT UX_USUARIO UNIQUE (usuario),
	CONSTRAINT FK_USU_IDI FOREIGN KEY (idioma_id) REFERENCES idiomas(id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla usuarios-roles
CREATE TABLE usuarios_roles(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	usuario_id INT UNSIGNED NOT NULL,
	rol_id INT UNSIGNED NOT NULL,
	CONSTRAINT FK_USUROL_USU FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_USUROL_ROL FOREIGN KEY (rol_id) REFERENCES roles(id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla eventos
CREATE TABLE eventos(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    detalles VARCHAR(200) NOT NULL,
    fecha_hora DATETIME NOT NULL,
    telefono_contacto CHAR(9) NOT NULL,
    localizacion VARCHAR(100) NOT NULL,
    latitud FLOAT NOT NULL,
    longitud FLOAT NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla usuarios-eventos
CREATE TABLE usuarios_eventos(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	usuario_id INT UNSIGNED NOT NULL,
	evento_id INT UNSIGNED NOT NULL,
	CONSTRAINT FK_USUEVE_USU FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_USUEVE_EVE FOREIGN KEY (evento_id) REFERENCES eventos(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla categorias
CREATE TABLE categorias(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    titulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    activo BOOLEAN NOT NULL,
    CONSTRAINT UX_TITULO_CAT UNIQUE (titulo)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;


-- Tabla intereses
CREATE TABLE intereses(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    titulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    activo BOOLEAN NOT NULL,
    categoria_id INT UNSIGNED NOT NULL,
    CONSTRAINT FK_INT_CAT FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UX_TITULO_INT UNIQUE (titulo)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla usuarios-intereses
CREATE TABLE usuarios_intereses(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	usuario_id INT UNSIGNED NOT NULL,
	interes_id INT UNSIGNED NOT NULL,
	CONSTRAINT FK_USUINT_USU FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
	CONSTRAINT FK_USUINT_INT FOREIGN KEY (interes_id) REFERENCES intereses(id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;

-- Tabla interes-eventos
CREATE TABLE intereses_eventos(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	interes_id INT UNSIGNED NOT NULL,
	evento_id INT UNSIGNED NOT NULL,
	CONSTRAINT FK_INTEVE_USU FOREIGN KEY (interes_id) REFERENCES intereses(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_INTEVE_EVE FOREIGN KEY (evento_id) REFERENCES eventos(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_spanish_ci;